build:
	dotnet build -c Release

test:
	dotnet test FormulaCalculator.Tests/FormulaCalculator.Tests.csproj -c Release -v detailed

benchmark:
	dotnet run -c Release --project FormulaCalculator.Benchmarks/FormulaCalculator.Benchmarks.csproj